config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
  get 'about', to: 'pages#about'

  # resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy] 
  # now we have all of resources so we don't need only to fix it
  resources :articles

  get 'signup', to: 'users#new'
  resources :users, except: [:new]

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'

  resources :categories
end

app/models/category.rb
class Category < ApplicationRecord
    validates :name, presence: true, length: { minimum: 3, maximum: 25 }
    validates_uniqueness_of :name
    has_many :article_categories
    has_many :articles, through: :article_categories
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :set_category, only: [:show, :edit, :update, :destroy]
    before_action :require_admin, except: [:index, :show]

    def new
        @category = Category.new
    end

    def create
        @category = Category.new(category_params)
        if @category.save
            flash[:notice] = "Category was successfully created"
            redirect_to @category
        else
            render 'new'
        end
    end

    def edit
    end

    def update
        if @category.update(category_params)
            flash[:notice] = "Updated successfully!"
            redirect_to @category
        else
            render 'edit'
        end
    end

    def destroy
        @category.destroy
        flash[:notice] = "Category has been deleted."
        redirect_to categories_path, status: :see_other
    end

    def index
        @categories = Category.paginate(page: params[:page], per_page: 5)
    end

    def show
        @category = Category.find(params[:id])
        @articles = @category.articles.paginate(page: params[:page], per_page: 5)
    end

    private

    def set_category
        @category = Category.find(params[:id])
    end

    def category_params
        params.require(:category).permit(:name)
    end

    def require_admin
        if !(logged_in? && current_user.admin?)
            flash[:alert] = "Only admins can perform that action"
            redirect_to categories_path
        end
    end
end

app/views/categories/_category.html.erb
<%= link_to category.name, category_path(category), class:"badge rounded-pill badge-info text-decoration-none mr-1" %>

app/views/categories/_form.html.erb
<%= render partial: "shared/errors", locals: { obj: @category } %>
<%= form_with(model: @category, data: { turbo: false }, class:"shadow p-3 mb-3 bg-dark rounded", local: true) do |f| %>
    <div class="form-group row">
        <%= f.label :name, "Category Name", class:"col-2 col-form-label text-light" %><br/>
        <div class="col-10">
            <%= f.text_field :name, class:"form-control shadow rounded", placeholder:"Enter a name" %>
        </div>
    </div>

    <div class="form-group row justify-content-center">
        <%= f.submit class:"col-2 btn btn-outline-light btn-lg" %>
    </div>

<% end %>

app/views/categories/edit.html.erb
<h1 class="text-center mt-4">Edit Category</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <%= render 'form' %>
        </div>
        <div class="mb-3">
            <%= link_to '[Return to Category]', category_path(@category), class: "link-danger" %>
        </div>
    </div>
</div>

app/views/categories/index.html.erb
<h1 class="text-center mt-4">Categories</h1>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

<div class="container">
    <% @categories.each do |category| %>
        <div class="row justify-content-md-center">
            <div class="col-4 mt-4">
                <div class="card text-center shadow mb-5 bg-white rounded">
                    <div class="card-body">
                        <h5 class="card-title"><%= link_to category.name, category_path(category), class:"text-success text-decoration-none" %></h5>
                        <p class="card-text text-warning"><%= pluralize(category.articles.count, "Article") %></p>
                    </div>

                    <div class="card-footer text-muted">
                        <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
                        edited <%= time_ago_in_words(category.updated_at) %> ago</small>
                    </div>
                </div>
            </div>
        </div>
    <% end %>
</div>

<div class="flickr_pagination">
    <%= will_paginate @categories, :container => false %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-4">Create Category</h1>

<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <%= render 'form' %>
        </div>
        <div class="mb-3">
                <%= link_to '[Return to View Categories]', categories_path, class: "link-danger" %>
        </div>
    </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-4">Category: <%= @category.name %></h1>

<% if logged_in? && current_user.admin? %>
    <div class="text-center mt-4">
        <%= link_to "Edit Category Name", edit_category_path(@category), class:"btn btn-outline-info" %>
        <%= link_to "Delete", category_path(@category), class:"btn btn-outline-danger", data: { turbo_method: :delete, turbo_confirm:"Confirm to delete this category?" } %>
    </div>
<% end %>

<h3 class="text-center mt-4">Articles</h3>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>

<%= render "articles/article" %>

<div class="flickr_pagination mb-4">
    <%= will_paginate @articles, :container => false %>
</div>